version: "3.2"
services:

  nginx:
    image: nginx:1.21.6
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./teampass/app:/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/etc/nginx/certs
    links:
      - teampass
    networks:
      - frontend

  teampass:
#    image: php:7-fpm
    build: teampass
    restart: always
    environment:
      - APP_PATH=/app
    volumes:
      - ./teampass/php/teampass-vars.ini:/usr/local/etc/php/conf.d/teampass-vars.ini
      - ./teampass/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./teampass/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

      - ./volumes/teampass/app:/app
      - ./volumes/teampass/sk/:/usr/local/teampass/sk/

      - .teampass/php/phpSettings.conf:/usr/local/etc/php-fpm.d/zzz-phpSettings.conf
      - ./logs/php-error.log:/var/log/error.log
      - ./logs/php-access.log:/var/log/access.log
    networks:
      - frontend
      - backend

  db:
    container_name: db
    restart: always
    image: mariadb:10.6
    command: --socket=/tmp/mariadb.sock
    environment:
      MARIADB_ROOT_PASSWORD: mypass
      MARIADB_DATABASE: teampass
      MARIADB_USER: teampass
      MARIADB_PASSWORD: teampass
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - backend

networks:
    frontend:
    backend: